name: DevSecOps Scans

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  gitleaks:
    name: Secrets (Gitleaks)
    runs-on: ubuntu-latest
    outputs:
      gate_fail: ${{ steps.eval.outputs.fail }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --redact --report-format sarif --report-path gitleaks.sarif
        continue-on-error: true
      - id: eval
        if: always()
        run: |
          if [ -f gitleaks.sarif ]; then CNT=$(jq '[.runs[].results[]] | length' gitleaks.sarif); else CNT=0; fi
          echo "fail=$([ "${CNT:-0}" -gt 0 ] && echo 1 || echo 0)" >> "$GITHUB_OUTPUT"
      - name: Upload SARIF (Gitleaks)
        if: always() && hashFiles('gitleaks.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

  semgrep:
    name: SAST (Semgrep)
    runs-on: ubuntu-latest
    outputs:
      gate_fail: ${{ steps.eval.outputs.fail }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten p/ci p/nodejs p/javascript
          generateSarif: true
        continue-on-error: true
      - name: Upload SARIF (Semgrep)
        if: always() && hashFiles('semgrep.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
      - id: eval
        if: always()
        run: |
          if [ -f semgrep.sarif ]; then
            HC=$(jq '[.runs[]?.results[]? | select((.properties.severity//""|ascii_upcase)=="HIGH" or (.properties.severity//""|ascii_upcase)=="CRITICAL" or (.level//""|ascii_downcase)=="error")] | length' semgrep.sarif)
          else HC=0; fi
          echo "fail=$([ "${HC:-0}" -gt 0 ] && echo 1 || echo 0)" >> "$GITHUB_OUTPUT"

  trivy_fs:
    name: Trivy FS
    runs-on: ubuntu-latest
    outputs:
      gate_fail: ${{ steps.eval.outputs.fail }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy (filesystem)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-fs.sarif
          security-checks: vuln,secret,config
          severity: HIGH,CRITICAL
          exit-code: 0
        continue-on-error: true
      - name: Upload SARIF (Trivy FS)
        if: always() && hashFiles('trivy-fs.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
      - id: eval
        if: always()
        run: |
          if [ -f trivy-fs.sarif ]; then CNT=$(jq '[.runs[].results[]] | length' trivy-fs.sarif); else CNT=0; fi
          echo "fail=$([ "${CNT:-0}" -gt 0 ] && echo 1 || echo 0)" >> "$GITHUB_OUTPUT"

  checkov_hadolint:
    name: IaC/Docker (Checkov + Hadolint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: dockerfile,compose
          output_format: sarif
          output_file_path: checkov.sarif
          soft_fail: true
      - name: Upload SARIF (Checkov)
        if: always() && hashFiles('checkov.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
        continue-on-error: true

  dast_zap:
    name: DAST (ZAP baseline)
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: ${{ secrets.STAGING_URL }}
          cmd_options: "-a -m 5 -r zap-report.html"
        continue-on-error: true
      - name: Ensure report exists
        run: '[ -f zap-report.html ] || echo "ZAP report not generated" > zap-report.html'
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html

  security_gate:
    name: security_gate
    runs-on: ubuntu-latest
    needs: [gitleaks, semgrep, trivy_fs, checkov_hadolint, dast_zap]
    steps:
      - name: Evaluate gate
        run: |
          echo "GITLEAKS=${{ needs.gitleaks.outputs.gate_fail }}"
          echo "SEMGREP=${{ needs.semgrep.outputs.gate_fail }}"
          echo "TRIVY=${{ needs.trivy_fs.outputs.gate_fail }}"
          FAILS=0
          [ "${{ needs.gitleaks.outputs.gate_fail }}" = "1" ] && FAILS=1
          [ "${{ needs.semgrep.outputs.gate_fail }}" = "1" ] && FAILS=1
          [ "${{ needs.trivy_fs.outputs.gate_fail }}" = "1" ] && FAILS=1
          if [ $FAILS -eq 1 ]; then echo "Security gate FAILED"; exit 1; else echo "Security gate PASSED"; fi

  render_deploy:
    name: Trigger Render deploy
    runs-on: ubuntu-latest
    needs: security_gate
    if: github.ref == 'refs/heads/master' && needs.security_gate.result == 'success'
    steps:
      - name: Ping Render deploy hook
        run: curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
